---
title: 'censo2017: Chilean Census 2017 Easy Access Database'
tags:
- R
- demographics
- reproducible research
authors:
- name: Mauricio Vargas Sepúlveda
  orcid: 0000-0003-1017-7574
  affiliation: 1
affiliations:
- name: Pontifical Catholic University of Chile
  index: 1
citation_author: Vargas et. al.
date: 30 October 2020
year: 2020
bibliography: paper.bib
output: rticles::joss_article
csl: apa.csl
journal: JOSS
---

# Summary

REDATAM [@redatam] is a widely used software for the dissemination of population censuses and it's free to use but it uses a closed format. @degrande2016 obtained a partial specification of this format and created a tool that allows exporting complete Redatam databases for its posterior use, for example, in R or Python.

`censo2017` is an R package designed to organize the Redatam files provided by the Chilean National Bureau of Statistics (*Instituto Nacional de Estadísticas de Chile* in spanish) in DVD format. This package was inspired by @ross2019citesdb who did something similar for a fauna and flora database.

This package creates a local and embedded SQLite database [@sqlite2020] that eases further analysis of the census datasets. It allows efficient querying and is accessible via a `DBI` compatible interface [@DBI]. The package also provides an interactive pane for RStudio [@rstudio] that allows exploring the database and previewing data.

# Acknowledgements

The author was able to complete this work by asking different geography-related questions to Juan Correa.

# References
